### ISSUE TITLE
what is P2R2 function in R script?

### ISSUE THREAD

**Issue by Kyung-TaeLee** [mrotival/EvoImmunoPop_Splicing#1]
Hi, thank you for your great work. 

In "01_MisoAggregate_Ens70_V7.R" script stored in "02_ASevents_Definition_and_Quantification" directory, can you tell me what P2R2 is? It seems like name of certain function but I can find it anywhere. The lines in which P2R2 appears are

R2Cont_notAdj=P2R2(pnorm(abs(VarBatch_notAdj[,-(1:8)]),low=F)*2,ncol(FPKM_gene),1)
R2Cont_Adj=P2R2(pnorm(abs(VarBatch_Adj[,-(1:8)]),low=F)*2,ncol(FPKM_gene),1)

They look like function to calculate R2 from t value of fixed effect in your linear fixed effect model. Hope you can tell me what they are. Thank you!

**Comment by mrotival** [comment]
Hello, 

my answer will probably arrive a bit late for your needs, but for the record P2R2 is indeed a fonction to obtain the R2 of a linear fixed effect model from the signifcance p-value

```
P2R2=function(p,n){
     qnorm(p/2)^2/(qnorm(p/2)^2+n)
}
```
